# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.7.3
      
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:  
          docker_layer_caching: true

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)
      - run: mix deps.get
      - run: mix compile
      - run: mix test
      - run: docker build -t larskj/plug-ex:1.0 .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PWD
      - run: docker push larskj/plug-ex:1.0

      - store_test_results:  # upload junit test results for display in Test Summary
          path: _build/test/lib/plug_ex